### ISSUE TITLE
Update Library: IOError 

### ISSUE THREAD

**Issue by NiceWavesSir** [zewt/zDsonImport#3]
While I was updating the library, I got an "IOError" 

# Error: IOError: file D:\Autodesk - Maya 2017 Win x64\Maya2017\bin\python27.zip\gzip.py line 197: Not a gzipped file # 

Sorry for disturbing, as I know your not supporting this product anymore, but I'll literally donate or pay to get this product to work. Seems awesome, thanks

**Comment by zewt** [comment]
Bug reports are fine, I just don't want people to expect a bunch of updates or anything like that.

Can you include the whole stack trace?  I can't tell where that's coming from.  I'm guessing there's a file in your library that looks like a compressed file but which actually isn't.  Also, check the output window for logs (it might show which file it was trying to read).

**Comment by NiceWavesSir** [comment]
```
file -f -new;
// untitled // 
commandPort -securityWarning -name commandportDefault;
onSetCurrentLayout "Maya Classic";
// Ornatrix: Using optimized viewport hair display mode.
// Ornatrix: Ornatrix 2.3.2.19004 Release initialized
Face Cap X loaded successfully.
// Warning: file: C:\Users\Gavin\Documents\maya\2019\prefs\filePathEditorRegistryPrefs.mel line 4: filePathEditor: Attribute 'aiImage.filename' is invalid or is not designated 'usedAsFilename'. // 
// Warning: file: C:\Users\Gavin\Documents\maya\2019\prefs\filePathEditorRegistryPrefs.mel line 5: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' is invalid or is not designated 'usedAsFilename'. // 
// Warning: file: C:\Users\Gavin\Documents\maya\2019\prefs\filePathEditorRegistryPrefs.mel line 6: filePathEditor: Attribute 'aiStandIn.dso' is invalid or is not designated 'usedAsFilename'. // 
// Warning: file: C:\Users\Gavin\Documents\maya\2019\prefs\filePathEditorRegistryPrefs.mel line 7: filePathEditor: Attribute 'aiVolume.filename' is invalid or is not designated 'usedAsFilename'. // 
// AbcExport v1.0 using Alembic 1.7.5 (built Feb  6 2018 18:28:08)
evalDeferred "shaderBallRendererMenuUpdate";
// Warning: line 1: filePathEditor: Attribute 'aiStandIn.dso' and label 'Standin' have been saved already. // 
// Warning: line 1: filePathEditor: Attribute 'aiVolume.filename' and label 'VDB' have been saved already. // 
// Warning: line 1: filePathEditor: Attribute 'aiImage.filename' and label 'Image' have been saved already. // 
// Warning: line 1: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' and label 'IES' have been saved already. // 
import arnold
// Successfully imported python module 'arnold'
import mtoa
// Successfully imported python module 'mtoa'
import mtoa.cmds.registerArnoldRenderer;mtoa.cmds.registerArnoldRenderer.registerArnoldRenderer()
// Successfully registered renderer 'arnold'
updateRenderOverride;
// Warning: file: D:/Audodesk/Maya 2019/Maya2019/scripts/startup/autoLoadPlugin.mel line 35: Loading plug-in "mtoa" has resulted in changes to the scene that may need to be saved. // 
// AbcImport v1.0 using Alembic 1.7.5 (built Feb  6 2018 18:28:08)
// Error: line 1: Plug-in, "KeyShot.mll", was not found on MAYA_PLUG_IN_PATH. // 
// Error: line 1: Invalid object or value: // 
// Error: line 1: Invalid object or value: // 
// Error: line 1: Plug-in, "KeyShot.mll", was not found on MAYA_PLUG_IN_PATH. // 
// Error: line 1: Invalid object or value: // 
// Error: line 1: Invalid object or value: // 
// Error: line 1: Plug-in, "KeyShot.mll", was not found on MAYA_PLUG_IN_PATH. // 
// Error: line 1: Invalid object or value: // 
// Error: line 1: Invalid object or value: // 
// Error: line 1: Plug-in, "KeyShot.mll", was not found on MAYA_PLUG_IN_PATH. // 
// Error: line 1: Invalid object or value: // 
// Error: line 1: Invalid object or value: // 
// Error: line 1: Plug-in, "KeyShot.mll", was not found on MAYA_PLUG_IN_PATH. // 
// Error: line 1: Invalid object or value: // 
// Error: line 1: Invalid object or value: // 
// Error: line 1: Plug-in, "KeyShot.mll", was not found on MAYA_PLUG_IN_PATH. // 
// Error: line 1: Invalid object or value: // 
// Error: line 1: Invalid object or value: // 
Menu: Not Found
None
Menu: Found!
menu32
[u'menuItem526', u'menuItem527']
DazToMaya
>> Import from DAZ Studio
updateRendererUI;
updateRendererUI;
# Error: ImportError: file <maya console> line 1: No module named aTools.animTools.animBar # 
# Error: ImportError: file <maya console> line 1: No module named aTools.animTools.animBar # 
# Error: ImportError: file <maya console> line 1: No module named aTools.animTools.animBar # 
// pymel.core : Updating pymel with pre-loaded plugins: mayaHIK, invertShape, curveWarp, hairPhysicalShader, ATFPlugin, ikSpringSolver, retargeterNodes, animBot_undoableCmd, lookdevKit, Type, Boss, meshReorder, modelingToolkit, MayaMuscle, matrixNodes, bifmeshio, deformerEvaluator, Ornatrix, shaderFXPlugin, objExport, bifrostshellnode, GPUBuiltInDeformer, svgFileTranslator, GamePipeline, tiffFloatReader, FaceCapX, MASH, poseInterpolator, bifrostvisplugin, cacheEvaluator, ik2Bsolver, xgenToolkit, AbcExport, VectorRender, gameFbxExporter, OpenEXRLoader, Unfold3D, mayaCharacterization, mtoa, rotateHelper, AbcImport, autoLoader, sceneAssembly, gpuCache, Substance, OneClick, DazToMaya, renderSetup, ArubaTessellator, quatNodes, fbxmaya
# DSONImporter : Refreshing asset cache...
# Error: IOError: file D:\Audodesk\Maya 2019\Maya2019\bin\python27.zip\gzip.py line 197: Not a gzipped file # 

```

Hmm, those last 2 lines seem to be the only lines regarding DSON. And nothing in my in my output window either. Anything else that I should check?

**Comment by NiceWavesSir** [comment]
Oh, it seems to give me the error once I get to a FBM (full body morphs) dsf file, I even deleted them so I could progress to the next dsf file, but the Full body morphs seem to give me problems

**Comment by zewt** [comment]
You might need to turn on "Show Stack Trace" in the history menu of the script editor, and make sure messages aren't suppressed.  I've updated asset scanning to handle read errors better, so it'll skip files that cause problems.  It's identifying a file as gzipped, but it's failing to decompress (hard to tell what the actual issue is without seeing the file--maybe a new compression method or something like that?)

**Comment by NiceWavesSir** [comment]
This is with "Show Stack Trace", I'll try out the update, thanks for the help dude
```
# DSONImporter : Refreshing asset cache... # 
# Error: Not a gzipped file
# Traceback (most recent call last):
#   File "D:\Audodesk\Maya 2019\Maya2019\Python\lib\site-packages\pymel\internal\factories.py", line 785, in callback
#     res = origCallback(*newargs)
#   File "E:/Downloads/zDsonImport-master/zDsonImport-master/plug-ins/zDsonImport.py", line 17, in do_update_library
#     ui.refresh_cache()
#   File "E:\Downloads\zDsonImport-master\zDsonImport-master\scripts\dsonimport\ui.py", line 1013, in refresh_cache
#     cache.scan(env, progress)
#   File "E:\Downloads\zDsonImport-master\zDsonImport-master\scripts\dsonimport\dson\content.py", line 478, in scan
#     if self._scan_asset(entry, relative_path, absolute_path):
#   File "E:\Downloads\zDsonImport-master\zDsonImport-master\scripts\dsonimport\dson\content.py", line 339, in _scan_asset
#     scan_modifier()
#   File "E:\Downloads\zDsonImport-master\zDsonImport-master\scripts\dsonimport\dson\content.py", line 310, in scan_modifier
#     asset_info = self._get_asset_info_fast(dson_file)
#   File "E:\Downloads\zDsonImport-master\zDsonImport-master\scripts\dsonimport\dson\content.py", line 263, in _get_asset_info_fast
#     data = dson_file.read(1024*4)
#   File "D:\Audodesk\Maya 2019\Maya2019\bin\python27.zip\gzip.py", line 268, in read
#     self._read(readsize)
#   File "D:\Audodesk\Maya 2019\Maya2019\bin\python27.zip\gzip.py", line 303, in _read
#     self._read_gzip_header()
#   File "D:\Audodesk\Maya 2019\Maya2019\bin\python27.zip\gzip.py", line 197, in _read_gzip_header
#     raise IOError, 'Not a gzipped file'
# IOError: Not a gzipped file # 
```

**Comment by NiceWavesSir** [comment]
Seem to be making progress , so it seems that my Animals are ruining the process? Here's both the Log File and history menu in the script editor

```
C:/Users/Gavin/Documents/DAZ 3D/Studio/My Library
C:/Users/Public/Documents/My DAZ 3D Library
E:/Documents/My DAZ 3D Library
C:/Users/Gavin/Documents/DAZ 3D/Studio/My Library
C:/Users/Public/Documents/My DAZ 3D Library
E:/Documents/My DAZ 3D Library
Refreshing asset cache...
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/alias_head_PHMCloseLeftEye.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/alias_head_PHMCloseRightEye.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/alias_head_PHMOpenMouth.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/alias_head_PHMSmallerEars.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/alias_head_PHMSquareMuzzle.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/alias_head_PHMSturdyHead.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PBMHipBulge.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PBMNeckBulge.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PBMOpenPouch.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PHMCloseLeftEye.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PHMCloseRightEye.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PHMOpenMouth.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PHMSmallerEars.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PHMSquareMuzzle.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PHMSturdyHead.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Baby/Morphs/Alessandro Mastronardi/Base/alias_head_PHMCloseLeftEye.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Baby/Morphs/Alessandro Mastronardi/Base/alias_head_PHMCloseRightEye.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Baby/Morphs/Alessandro Mastronardi/Base/alias_head_PHMOpenMouth.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Baby/Morphs/Alessandro Mastronardi/Base/PHMCloseLeftEye.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Baby/Morphs/Alessandro Mastronardi/Base/PHMCloseRightEye.dsf: Not a gzipped file
Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Baby/Morphs/Alessandro Mastronardi/Base/PHMOpenMouth.dsf: Not a gzipped file

```

```
Refreshing asset cache...
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/alias_head_PHMCloseLeftEye.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/alias_head_PHMCloseRightEye.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/alias_head_PHMOpenMouth.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/alias_head_PHMSmallerEars.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/alias_head_PHMSquareMuzzle.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/alias_head_PHMSturdyHead.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PBMHipBulge.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PBMNeckBulge.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PBMOpenPouch.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PHMCloseLeftEye.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PHMCloseRightEye.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PHMOpenMouth.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PHMSmallerEars.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PHMSquareMuzzle.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Adult/Morphs/Alessandro Mastronardi/Base/PHMSturdyHead.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Baby/Morphs/Alessandro Mastronardi/Base/alias_head_PHMCloseLeftEye.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Baby/Morphs/Alessandro Mastronardi/Base/alias_head_PHMCloseRightEye.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Baby/Morphs/Alessandro Mastronardi/Base/alias_head_PHMOpenMouth.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Baby/Morphs/Alessandro Mastronardi/Base/PHMCloseLeftEye.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Baby/Morphs/Alessandro Mastronardi/Base/PHMCloseRightEye.dsf: Not a gzipped file # 
# Warning: Error reading E:/Documents/My DAZ 3D Library/data/Alessandro Mastronardi/Kangaroos by AM/Kangaroo - Red Baby/Morphs/Alessandro Mastronardi/Base/PHMOpenMouth.dsf: Not a gzipped file # 
# Error: Expecting , delimiter: line 44 column 20 (char 1168)
# Traceback (most recent call last):
#   File "D:\Audodesk\Maya 2018\Maya2018\Python\lib\site-packages\pymel\internal\factories.py", line 785, in callback
#     res = origCallback(*newargs)
#   File "E:/Downloads/zDsonImport-master (1)/zDsonImport-master/plug-ins/zDsonImport.py", line 19, in do_update_library
#     ui.refresh_cache()
#   File "E:\Downloads\zDsonImport-master (1)\zDsonImport-master\scripts\dsonimport\ui.py", line 1013, in refresh_cache
#     cache.scan(env, progress)
#   File "E:\Downloads\zDsonImport-master (1)\zDsonImport-master\scripts\dsonimport\dson\content.py", line 482, in scan
#     if self._scan_asset(entry, relative_path, absolute_path):
#   File "E:\Downloads\zDsonImport-master (1)\zDsonImport-master\scripts\dsonimport\dson\content.py", line 340, in _scan_asset
#     scan_modifier()
#   File "E:\Downloads\zDsonImport-master (1)\zDsonImport-master\scripts\dsonimport\dson\content.py", line 316, in scan_modifier
#     json_data = json.loads(data)
#   File "D:\Audodesk\Maya 2018\Maya2018\bin\python27.zip\json\__init__.py", line 339, in loads
#     return _default_decoder.decode(s)
#   File "D:\Audodesk\Maya 2018\Maya2018\bin\python27.zip\json\decoder.py", line 364, in decode
#     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
#   File "D:\Audodesk\Maya 2018\Maya2018\bin\python27.zip\json\decoder.py", line 380, in raw_decode
#     obj, end = self.scan_once(s, idx)
# ValueError: Expecting , delimiter: line 44 column 20 (char 1168) # 
```

**Comment by zewt** [comment]
I fixed the error handling so JSON errors there will just ignore that asset and continue.  I can't tell what's actually wrong with these files since I don't have these assets, but it should get you closer.

**Comment by NiceWavesSir** [comment]
Hmm, didn't know hair had JCMs. 

`````
Error reading asset E:/Documents/My DAZ 3D Library/data/AprilYSH/ColeraineGenesis/ColeraineHairG3F/Morphs/AprilYSH/Base/pJCMNeckFwd_35.dsf: Expecting , delimiter: line 44 column 20 (char 1168).  Ignoring this asset.
# Error: (u'/data/AprilYSH/PascaleGenesis/PascaleHairG8F/Morphs/AprilYSH/Base/pJCMHeadBack_27.dsf', u'#aprilyshPascaleHairG8F')
# Traceback (most recent call last):
#   File "D:\Audodesk\Maya 2018\Maya2018\Python\lib\site-packages\pymel\internal\factories.py", line 785, in callback
#     res = origCallback(*newargs)
#   File "E:/Downloads/zDsonImport-master/zDsonImport-master/plug-ins/zDsonImport.py", line 19, in do_update_library
#     ui.refresh_cache()
#   File "E:\Downloads\zDsonImport-master\zDsonImport-master\scripts\dsonimport\ui.py", line 1013, in refresh_cache
#     cache.scan(env, progress)
#   File "E:\Downloads\zDsonImport-master\zDsonImport-master\scripts\dsonimport\dson\content.py", line 486, in scan
#     if self._scan_asset(entry, relative_path, absolute_path):
#   File "E:\Downloads\zDsonImport-master\zDsonImport-master\scripts\dsonimport\dson\content.py", line 344, in _scan_asset
#     scan_modifier()
#   File "E:\Downloads\zDsonImport-master\zDsonImport-master\scripts\dsonimport\dson\content.py", line 334, in scan_modifier
#     info = self.cache_modifier_info(relative_path, modifier)
#   File "E:\Downloads\zDsonImport-master\zDsonImport-master\scripts\dsonimport\dson\content.py", line 373, in cache_modifier_info
#     assert parsed_url.path, (relative_path, parent_url)
# AssertionError: (u'/data/AprilYSH/PascaleGenesis/PascaleHairG8F/Morphs/AprilYSH/Base/pJCMHeadBack_27.dsf', u'#aprilyshPascaleHairG8F') # 
```
Log File:
`Error reading asset E:/Documents/My DAZ 3D Library/data/AprilYSH/ColeraineGenesis/ColeraineHairG3F/Morphs/AprilYSH/Base/pJCMNeckFwd_35.dsf: Expecting , delimiter: line 44 column 20 (char 1168).  Ignoring this asset.`

**Comment by NiceWavesSir** [comment]
Maybe I can send you these files so you can decipher the problem that it's causing
